import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildQikinkOrderPayload, buildQikinkStoreOrderPayload, qikinkOrderNumber } from '../lib/qikink/payload.ts';
import { MemoryQikinkSubmissionStore, withQikinkIdempotency } from '../lib/qikink/idempotency.ts';

const order = (paymentMethod: 'cod' | 'prepaid' = 'prepaid') => ({ orderId: 'CC-12345678-EXTRA-LONG', paymentMethod, total: 1299, shippingAddress: { firstName: 'CASECLAN', lastName: 'Sandbox', address1: 'Test Address', phone: '9999999999', email: 'sandbox@caseclan.test', city: 'Chennai', postalCode: '600001', state: 'Tamil Nadu' }, items: [{ qikinkSku: 'provider-store-sku', quantity: 1, price: 1299, printTypeId: 5, designCode: 'CCSBX17', placementSku: 'acc', printArtworkUrl: 'https://caseclan.vercel.app/art.png', previewUrl: 'https://caseclan.vercel.app/preview.png' }] });

test('maps COD and prepaid without changing shipping or artwork URLs', () => { const prepaid = buildQikinkOrderPayload(order('prepaid')); const cod = buildQikinkOrderPayload(order('cod')); assert.equal(prepaid.gateway, 'Prepaid'); assert.equal(cod.gateway, 'COD'); assert.equal(prepaid.shipping_address.country_code, 'IN'); assert.equal(prepaid.line_items[0].designs[0].design_link, 'https://caseclan.vercel.app/art.png'); });
test('Store SKU mode omits design details because Qikink owns the linked artwork', () => { const payload = buildQikinkStoreOrderPayload(order()); assert.deepEqual(payload.line_items[0], { search_from_my_products: 1, quantity: '1', price: '1299', sku: 'provider-store-sku' }); });
test('normalizes provider order numbers to 15 alphanumeric characters', () => { assert.match(qikinkOrderNumber('CC-12345678-EXTRA-LONG'), /^[A-Z0-9]{1,15}$/); });
test('fails closed when provider SKU or public artwork is missing', () => { const missingSku = order(); missingSku.items[0].qikinkSku = ''; assert.throws(() => buildQikinkOrderPayload(missingSku), /Missing Qikink Store SKU/); const localArtwork = order(); localArtwork.items[0].printArtworkUrl = 'http://localhost/art.png'; assert.throws(() => buildQikinkOrderPayload(localArtwork), /must use HTTPS/); });
test('idempotency store prevents a second claim after success', async () => { const store = new MemoryQikinkSubmissionStore<{ order_id: number }>(); assert.equal(await store.claim('qikink:sandbox:CC123'), true); await store.succeed('qikink:sandbox:CC123', { order_id: 42 }); assert.equal(await store.claim('qikink:sandbox:CC123'), false); assert.deepEqual(await store.get('qikink:sandbox:CC123'), { state: 'succeeded', response: { order_id: 42 } }); });
test('duplicate order submission calls Qikink only once', async () => { const store = new MemoryQikinkSubmissionStore<{ order_id: number }>(); let calls = 0; const submit = () => withQikinkIdempotency('qikink:sandbox:CC123', store, async () => { calls += 1; return { order_id: 42 }; }); const first = await submit(); const replay = await submit(); assert.equal(first.duplicate, false); assert.equal(replay.duplicate, true); assert.equal(calls, 1); });
test('Qikink secrets remain server-only and use no NEXT_PUBLIC names', () => { const source = readFileSync(join(process.cwd(), 'lib/qikink/client.ts'), 'utf8'); assert.match(source, /import 'server-only'/); assert.doesNotMatch(source, /NEXT_PUBLIC_QIKINK/); });
test('automatic Qikink submission is disabled unless a server flag explicitly enables it', () => { const source = readFileSync(join(process.cwd(), 'lib/qikink/client.ts'), 'utf8'); assert.match(source, /QIKINK_AUTOMATIC_FULFILMENT !== 'true'/); });
test('phone SKU mappings have one server-only source of truth', () => { const source = readFileSync(join(process.cwd(), 'lib/qikink/fulfillment-config.ts'), 'utf8'); assert.match(source, /import 'server-only'/); assert.match(source, /QIKINK_SANDBOX_PHONE_SKU_IPHONE_17_PRO_MAX/); assert.doesNotMatch(source, /v-[A-Za-z0-9]/); });
