import {commerceConfig} from '@/lib/commerce';

export const faqGroups=[
 {title:'ORDERS',items:[['How can I place an order?','Choose a fixed design or create a custom case, select the exact phone model, add it to your cart and continue through checkout.'],['Can I modify my order?','Order changes require support review. Live modification rules will be published before production orders open.'],['How do I track my order?','Open Track Order and enter the order ID with the matching email or phone number.']]},
 {title:'CUSTOM CASES',items:[['How does Design Your Own work?','Choose your phone on the homepage, open the blank editor, then add and arrange text, images or graphics.'],['What image quality should I upload?','Use the largest original image available. The editor warns when the effective print resolution may appear blurry.'],['Can I move or resize my image?','Yes. Drag, zoom, resize and rotate your image. Fit to Case restores the recommended full-bleed crop.']]},
 {title:'PHONE MODELS',items:[['How do I select my phone model?','Use Choose Your Model on the homepage or the model selector on a ready-design product page.'],['What if my model is unavailable?','Do not select a similar model. Contact support or check back as new model-specific case assets are added.']]},
 {title:'PAYMENTS',items:[['Is COD available?','Cash on Delivery is prepared as a checkout option. Final availability is confirmed when live ordering launches.'],['Which online payment methods are supported?','A payment provider has not been connected yet. Supported methods will be listed before payments are enabled.']]},
 {title:'SHIPPING',items:[['How long does delivery take?',commerceConfig.deliveryEstimate],['How will I receive tracking?','Tracking details will appear against your order when a courier and tracking ID are available.']]},
 {title:'RETURNS',items:[['What if I receive a damaged product?','Contact support with your order details and clear photos. Eligibility and resolution depend on the published policy at the time of purchase.'],['Are custom cases returnable?','Custom-product eligibility will be stated clearly before checkout when production ordering becomes available.']]},
] as const;
