'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {safeNextPath} from '@/lib/auth';
import {useAuth} from './AuthProvider';

export function AuthForm({mode}:{mode:'login'|'signup'|'forgot'}){const auth=useAuth(),router=useRouter(),params=useSearchParams(),next=safeNextPath(params.get('next'),'/account/'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{if(auth.ready&&auth.user&&mode!=='forgot')router.replace(next)},[auth.ready,auth.user,mode,next,router]);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setNotice('');if(mode==='forgot'){const error=await auth.sendReset(email);setNotice(error||'Check your email for a secure password-reset link.');setBusy(false);return}if(mode==='signup'){const result=await auth.signUp(email,password,name,`${location.origin}/login/?next=${encodeURIComponent(next)}`);if(result.error)setNotice(result.error);else if(result.needsConfirmation)setNotice('Account created. Check your email to confirm it, then sign in.');else router.replace(next);setBusy(false);return}const error=await auth.signIn(email,password);if(error){setNotice(error);setBusy(false)}else router.replace(next)};const heading=mode==='login'?'Welcome back.':mode==='signup'?'Create your account.':'Reset your password.';return <><div className="page-intro auth-intro"><p className="eyebrow">YOUR CASECLAN ACCOUNT</p><h1>{heading}</h1><p>{mode==='forgot'?'We will email you a secure reset link.':'Your cart and custom design stay on this device while you sign in.'}</p></div><section className="auth-card"><form onSubmit={submit}>{mode==='signup'&&<label className="field-label">Full name<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label className="field-label">Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='forgot'&&<label className="field-label">Password<input required type="password" minLength={8} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button disabled={busy} className="button wide">{busy?'PLEASE WAIT…':mode==='login'?'LOGIN':mode==='signup'?'CREATE ACCOUNT':'SEND RESET LINK'}</button></form>{notice&&<p className="form-note" role="status">{notice}</p>}<div className="auth-links">{mode!=='forgot'&&<Link href={`/forgot-password/?next=${encodeURIComponent(next)}`}>Forgot password</Link>}{mode!=='signup'&&<Link href={`/signup/?next=${encodeURIComponent(next)}`}>Create account</Link>}{mode!=='login'&&<Link href={`/login/?next=${encodeURIComponent(next)}`}>Back to login</Link>}</div></section></>}

export function ResetPassword(){const auth=useAuth(),router=useRouter(),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password!==confirm){setNotice('Passwords do not match.');return}setBusy(true);const error=await auth.updatePassword(password);setNotice(error||'Password updated. Redirecting to your account…');setBusy(false);if(!error)setTimeout(()=>router.replace('/account/'),700)};return <><div className="page-intro auth-intro"><p className="eyebrow">SECURE ACCOUNT RECOVERY</p><h1>Choose a new password.</h1></div><section className="auth-card"><form onSubmit={submit}><label className="field-label">New password<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field-label">Confirm password<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={busy} className="button wide">UPDATE PASSWORD</button></form>{notice&&<p className="form-note" role="status">{notice}</p>}</section></>}
