'use client';

import {PointerEvent as ReactPointerEvent,useCallback,useEffect,useRef,useState} from 'react';
import {Customization,Layer,constrainLayer,hitLayer,modelConfig,renderArtwork} from '@/lib/customizer';

type Props={design:Customization;selected?:string;guides?:boolean;editing?:boolean;view?:string;onSelect?:(id:string)=>void;onMove?:(layer:Layer,commit:boolean)=>void;onCapture?:(capture:()=>string)=>void};
type Frame={x:number;y:number;w:number;h:number;angle:number;skew:number};

const VIEW:Record<string,{angle:number;skew:number;scale:number}>={Front:{angle:0,skew:0,scale:1},Angle:{angle:-.045,skew:-.10,scale:.96},Left:{angle:.035,skew:.09,scale:.95},Right:{angle:-.035,skew:-.09,scale:.95},Top:{angle:-.018,skew:-.04,scale:.92},Bottom:{angle:.018,skew:.04,scale:.92}};

function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(r,w/2,h/2))}
function layout(size:{width:number;height:number},design:Customization,view:string):Frame{const p=VIEW[view]||VIEW.Front,maxH=size.height*.79,maxW=size.width*.48,ratio=modelConfig(design.device).width/modelConfig(design.device).height;const h=Math.min(maxH,maxW/ratio)*p.scale,w=h*ratio;return {x:(size.width-w)/2,y:(size.height-h)/2-6,w,h,angle:p.angle,skew:p.skew}}
function lens(ctx:CanvasRenderingContext2D,x:number,y:number,r:number){const metal=ctx.createRadialGradient(x-r*.25,y-r*.35,r*.08,x,y,r);metal.addColorStop(0,'#f8fafb');metal.addColorStop(.42,'#a6abb0');metal.addColorStop(.56,'#202326');metal.addColorStop(.7,'#020304');metal.addColorStop(1,'#090b0e');ctx.fillStyle=metal;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=Math.max(1,r*.055);ctx.stroke();const glass=ctx.createRadialGradient(x-r*.18,y-r*.2,0,x,y,r*.63);glass.addColorStop(0,'#5278a0');glass.addColorStop(.16,'#152b45');glass.addColorStop(.48,'#05080e');glass.addColorStop(1,'#010204');ctx.fillStyle=glass;ctx.beginPath();ctx.arc(x,y,r*.63,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(140,185,225,.38)';ctx.beginPath();ctx.ellipse(x-r*.18,y-r*.22,r*.12,r*.07,-.5,0,Math.PI*2);ctx.fill()}
function drawCamera(ctx:CanvasRenderingContext2D,d:Customization,f:Frame){const c=modelConfig(d.device),sx=f.w/1000,sy=f.h/2000,box={x:f.x+c.camera.x*sx,y:f.y+c.camera.y*sy,w:c.camera.width*sx,h:c.camera.height*sy},wide=c.cameraLayout==='triple-wide';ctx.save();ctx.shadowColor='rgba(0,0,0,.34)';ctx.shadowBlur=f.w*.035;ctx.shadowOffsetY=f.w*.014;rounded(ctx,box.x,box.y,box.w,box.h,Math.min(box.w,box.h)*(wide?.18:.22));const plate=ctx.createLinearGradient(box.x,box.y,box.x+box.w,box.y+box.h);plate.addColorStop(0,'#e8e8e5');plate.addColorStop(.45,'#aeb0b2');plate.addColorStop(1,'#e6e6e4');ctx.fillStyle=plate;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(10,12,14,.9)';ctx.lineWidth=Math.max(3,f.w*.014);ctx.stroke();const r=Math.min(box.w,box.h)*(wide?.25:c.cameraLayout==='dual-vertical'?.22:.25);let pts:[number,number][]=[];if(c.cameraLayout==='triple-wide')pts=[[.21,.36],[.5,.58],[.79,.36]];else if(c.cameraLayout==='triple-square')pts=[[.31,.29],[.69,.48],[.31,.72]];else if(c.cameraLayout==='dual-vertical')pts=[[.5,.28],[.5,.72]];else pts=[[.31,.31],[.69,.69]];for(const [px,py] of pts)lens(ctx,box.x+box.w*px,box.y+box.h*py,r);const flashX=box.x+box.w*(wide?.89:.76),flashY=box.y+box.h*(wide?.72:.22);ctx.fillStyle='#f6ead1';ctx.beginPath();ctx.arc(flashX,flashY,r*.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f9f9f7';ctx.lineWidth=2;ctx.stroke();if(c.cameraLayout.includes('triple')){ctx.fillStyle='#111';ctx.beginPath();ctx.arc(box.x+box.w*(wide?.9:.77),box.y+box.h*(wide?.42:.76),r*.22,0,Math.PI*2);ctx.fill()}ctx.restore()}
async function paint(canvas:HTMLCanvasElement,d:Customization,selected:string|undefined,guides:boolean,view:string){const dpr=Math.min(2,window.devicePixelRatio||1),cssW=Math.max(320,canvas.clientWidth||720),cssH=Math.max(420,canvas.clientHeight||820);if(canvas.width!==Math.round(cssW*dpr)||canvas.height!==Math.round(cssH*dpr)){canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr)}const ctx=canvas.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cssW,cssH);const art=await renderArtwork(d,1000,guides,selected),f=layout({width:cssW,height:cssH},d,view),c=modelConfig(d.device);const bg=ctx.createRadialGradient(cssW*.48,cssH*.42,10,cssW*.5,cssH*.48,cssW*.56);bg.addColorStop(0,'rgba(255,255,255,.98)');bg.addColorStop(.55,'rgba(232,231,228,.92)');bg.addColorStop(1,'rgba(205,203,200,.72)');ctx.fillStyle=bg;ctx.fillRect(0,0,cssW,cssH);ctx.fillStyle='rgba(0,0,0,.18)';ctx.filter='blur(18px)';ctx.beginPath();ctx.ellipse(cssW*.5,f.y+f.h+22,f.w*.66,18,0,0,Math.PI*2);ctx.fill();ctx.filter='none';ctx.save();ctx.translate(cssW/2,cssH/2);ctx.rotate(f.angle);ctx.transform(1,0,f.skew,1,0,0);ctx.translate(-cssW/2,-cssH/2);ctx.shadowColor='rgba(0,0,0,.30)';ctx.shadowBlur=30;ctx.shadowOffsetX=view==='Left'?-14:14;ctx.shadowOffsetY=20;rounded(ctx,f.x-9,f.y-9,f.w+18,f.h+18,c.cornerRadius*f.w/1000+9);const edge=ctx.createLinearGradient(f.x,f.y,f.x+f.w,f.y+f.h);edge.addColorStop(0,'rgba(245,248,249,.98)');edge.addColorStop(.22,'rgba(95,100,104,.94)');edge.addColorStop(.48,'rgba(20,22,24,.98)');edge.addColorStop(.77,'rgba(125,130,134,.95)');edge.addColorStop(1,'rgba(246,248,249,.96)');ctx.fillStyle=edge;ctx.fill();ctx.shadowColor='transparent';rounded(ctx,f.x-3,f.y-3,f.w+6,f.h+6,c.cornerRadius*f.w/1000+3);ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=3;ctx.stroke();rounded(ctx,f.x,f.y,f.w,f.h,c.cornerRadius*f.w/1000);ctx.save();ctx.clip();ctx.drawImage(art,f.x,f.y,f.w,f.h);const sheen=ctx.createLinearGradient(f.x,f.y,f.x+f.w,f.y);sheen.addColorStop(0,'rgba(255,255,255,.07)');sheen.addColorStop(.56,'rgba(255,255,255,0)');sheen.addColorStop(.72,'rgba(255,255,255,.13)');sheen.addColorStop(1,'rgba(255,255,255,.03)');ctx.fillStyle=sheen;ctx.fillRect(f.x,f.y,f.w,f.h);ctx.restore();ctx.strokeStyle='rgba(255,255,255,.38)';ctx.lineWidth=2;rounded(ctx,f.x+3,f.y+3,f.w-6,f.h-6,c.cornerRadius*f.w/1000-2);ctx.stroke();drawCamera(ctx,d,f);ctx.fillStyle='rgba(25,27,29,.9)';rounded(ctx,f.x-12,f.y+f.h*.28,8,f.h*.13,4);ctx.fill();rounded(ctx,f.x+f.w+4,f.y+f.h*.22,8,f.h*.16,4);ctx.fill();ctx.restore()}

export default function CaseScene(props:Props){const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{layer:Layer;x:number;y:number;latest:Layer;mode:'move'|'scale'}|null>(null),[loading,setLoading]=useState(true);const redraw=useCallback(()=>{if(!canvas.current)return;paint(canvas.current,props.design,props.selected,!!props.guides,props.view||'Front').then(()=>setLoading(false))},[props.design,props.selected,props.guides,props.view]);useEffect(()=>{redraw();const el=canvas.current;if(!el)return;const observer=new ResizeObserver(redraw);observer.observe(el);return()=>observer.disconnect()},[redraw]);useEffect(()=>{props.onCapture?.(()=>canvas.current?.toDataURL('image/webp',.9)||'')},[props.onCapture,props.design,props.view]);const point=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const el=canvas.current!,rect=el.getBoundingClientRect(),f=layout({width:rect.width,height:rect.height},props.design,props.view||'Front');return {x:(e.clientX-rect.left-f.x)/f.w*1000,y:(e.clientY-rect.top-f.y)/f.h*2000}};const down=(e:ReactPointerEvent<HTMLCanvasElement>)=>{if(!props.editing)return;const p=point(e),layer=hitLayer(props.design.layers,p.x,p.y);if(!layer)return;props.onSelect?.(layer.id);const scale=Math.abs(p.x-layer.x)>layer.width*.36&&Math.abs(p.y-layer.y)>layer.height*.3;drag.current={layer,x:p.x,y:p.y,latest:layer,mode:scale?'scale':'move'};e.currentTarget.setPointerCapture(e.pointerId)};const move=(e:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drag.current||!props.editing)return;const p=point(e),d=drag.current,next=constrainLayer(d.mode==='scale'?{...d.layer,width:Math.max(70,Math.abs(p.x-d.layer.x)*2),height:Math.max(50,Math.abs(p.y-d.layer.y)*2)}:{...d.layer,x:d.layer.x+p.x-d.x,y:d.layer.y+p.y-d.y},props.design.device);d.latest=next;props.onMove?.(next,false)};const up=(e:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drag.current)return;props.onMove?.(drag.current.latest,true);drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId)};return <div className="case-scene realistic-mockup" aria-label={`Realistic ${props.design.device} phone case preview`}><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/>{loading&&<p className="scene-loading">Compositing your case…</p>}<span className="mockup-badge">2.5D PRODUCT PREVIEW</span></div>}
