'use client';
import {Canvas,ThreeEvent,useThree} from '@react-three/fiber';
import {OrbitControls,RoundedBox,useGLTF,ContactShadows,Html} from '@react-three/drei';
import {CanvasTexture,SRGBColorSpace,Mesh,MeshStandardMaterial,Vector3} from 'three';
import {Component,ReactNode,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Customization,Layer,constrainLayer,hitLayer,modelConfig,renderArtwork} from '@/lib/customizer';
type Props={design:Customization;selected?:string;guides?:boolean;editing?:boolean;view?:string;onSelect?:(id:string)=>void;onMove?:(layer:Layer,commit:boolean)=>void;onCapture?:(capture:()=>string)=>void};
function CameraView({view,editing}:{view:string;editing:boolean}){const {camera,controls,invalidate}=useThree();useEffect(()=>{const positions:Record<string,number[]>={Front:[0,0,8.8],Left:[-10,0,0],Right:[10,0,0],Top:[0,10,.01],Bottom:[0,-10,.01],Angle:[3.3,.8,8.8]};const p=positions[editing?'Front':view]||positions.Front;camera.position.set(p[0],p[1],p[2]);camera.lookAt(0,0,0);(controls as unknown as {target?:Vector3;update?:()=>void})?.target?.set(0,0,0);(controls as unknown as {update?:()=>void})?.update?.();invalidate()},[camera,controls,editing,view,invalidate]);return null}
function Capture({onCapture}:{onCapture?:Props['onCapture']}){const {gl,scene,camera}=useThree();useEffect(()=>{onCapture?.(()=>{gl.render(scene,camera);return gl.domElement.toDataURL('image/webp',.85)})},[gl,scene,camera,onCapture]);return null}
function SuppliedModel({url,texture,meshName,events}:{url:string;texture:CanvasTexture;meshName:string;events:Record<string,(e:ThreeEvent<PointerEvent>)=>void>}){const {scene}=useGLTF(url);const model=useMemo(()=>{const copy=scene.clone(true);copy.traverse(obj=>{if(obj instanceof Mesh&&obj.name===meshName){obj.material=new MeshStandardMaterial({map:texture,roughness:.8});}});return copy},[scene,texture,meshName]);return <primitive object={model} {...events}/>}
function Case({design,selected,guides,editing,onSelect,onMove}:Props){const c=modelConfig(design.device);const [texture,setTexture]=useState<CanvasTexture|null>(null);const drag=useRef<{layer:Layer;x:number;y:number;latest:Layer;mode:'move'|'scale'}|null>(null);useEffect(()=>{let active=true;let created:CanvasTexture|undefined;renderArtwork(design,1024,guides,selected).then(canvas=>{if(!active)return;created=new CanvasTexture(canvas);created.colorSpace=SRGBColorSpace;created.flipY=!c.url;setTexture(created)});return()=>{active=false;created?.dispose()}},[design,guides,selected]);
const point=(e:ThreeEvent<PointerEvent>)=>{if(c.url&&e.uv)return {x:e.uv.x*1000,y:e.uv.y*2000};const p=e.point.clone();return {x:(p.x/c.width+.5)*1000,y:(.5-p.y/c.height)*2000}};
const down=(e:ThreeEvent<PointerEvent>)=>{if(!editing||(c.url&&e.object.name!==c.printMesh))return;e.stopPropagation();const p=point(e);const layer=hitLayer(design.layers,p.x,p.y);if(!layer)return;onSelect?.(layer.id);const b=Math.abs(p.x-layer.x)>layer.width*.36&&Math.abs(p.y-layer.y)>layer.height*.30;drag.current={layer,x:p.x,y:p.y,latest:layer,mode:b?'scale':'move'};(e.target as unknown as Element).setPointerCapture(e.pointerId)};
const move=(e:ThreeEvent<PointerEvent>)=>{if(!drag.current||!editing)return;e.stopPropagation();const p=point(e),d=drag.current;const next=constrainLayer(d.mode==='scale'?{...d.layer,width:Math.max(70,Math.abs(p.x-d.layer.x)*2),height:Math.max(50,Math.abs(p.y-d.layer.y)*2)}:{...d.layer,x:d.layer.x+p.x-d.x,y:d.layer.y+p.y-d.y},design.device);d.latest=next;onMove?.(next,false)};
const up=(e:ThreeEvent<PointerEvent>)=>{if(!drag.current)return;e.stopPropagation();onMove?.(drag.current.latest,true);drag.current=null;(e.target as unknown as Element).releasePointerCapture(e.pointerId)};
if(!texture)return null;
if(c.url)return <SuppliedModel url={c.url} texture={texture} meshName={c.printMesh} events={{onPointerDown:down,onPointerMove:move,onPointerUp:up,onPointerCancel:up}}/>;
const cameraX=(c.camera.x+c.camera.width/2-500)/1000*c.width,cameraY=(1000-c.camera.y-c.camera.height/2)/2000*c.height;
return <group>
 <RoundedBox args={[c.width+.12,c.height+.12,.30]} radius={.22} smoothness={6}><meshStandardMaterial color="#151619" roughness={.46} metalness={.3}/></RoundedBox>
 <mesh position={[0,0,.164]} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><planeGeometry args={[c.width,c.height]}/><meshStandardMaterial map={texture} transparent roughness={.86} metalness={.04}/></mesh>
 <RoundedBox args={[c.camera.width/1000*c.width,c.camera.height/2000*c.height,.17]} radius={.15} position={[cameraX,cameraY,.24]}><meshStandardMaterial color="#74777a" roughness={.3} metalness={.8}/></RoundedBox>
 {(design.device.includes('pro')?[[0,0],[0,1],[1,.5]]:[[0,0],[0,1]]).map(([x,y],i)=><group key={i} position={[cameraX+(x-.4)*.61,cameraY+(.5-y)*.66,.38]}><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.26,.26,.09,48]} /><meshStandardMaterial color="#b9babc" metalness={.9} roughness={.2}/></mesh><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.24,.24,.08,48]}/><meshStandardMaterial color="#05070b" roughness={.14} metalness={.7}/></mesh><mesh position={[0,0,.045]}><circleGeometry args={[.12,40]}/><meshStandardMaterial color="#08172c" roughness={.08} metalness={.8}/></mesh><mesh position={[-.045,.04,.05]}><circleGeometry args={[.035,24]}/><meshBasicMaterial color="#7494b8"/></mesh></group>)}
 <RoundedBox args={[.07,.7,.16]} position={[-c.width/2-.07,.55,0]} radius={.03}><meshStandardMaterial color="#27282a" metalness={.6}/></RoundedBox>
 <RoundedBox args={[.07,.6,.16]} position={[c.width/2+.07,.7,0]} radius={.03}><meshStandardMaterial color="#27282a" metalness={.6}/></RoundedBox>
 <RoundedBox args={[c.width-.18,c.height-.18,.03]} position={[0,0,-.17]} radius={.2}><meshStandardMaterial color="#060608" roughness={.12} metalness={.5}/></RoundedBox>
 <RoundedBox args={[.65,.13,.04]} position={[0,c.height/2-.27,-.2]} radius={.06}><meshStandardMaterial color="#000"/></RoundedBox>
 </group>}
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
export default function CaseScene(props:Props){const [supported,setSupported]=useState<boolean|null>(null),[fallback,setFallback]=useState('');useEffect(()=>{const c=document.createElement('canvas');const gl=c.getContext('webgl2');setSupported(!!gl);gl?.getExtension('WEBGL_lose_context')?.loseContext()},[]);useEffect(()=>{let active=true;renderArtwork(props.design,512).then(c=>{if(active)setFallback(c.toDataURL())});return()=>{active=false}},[props.design]);const fail=<div className="scene-fallback"><img src={fallback||'/assets/designs/minimal-name.webp'} alt="Flat artwork preview"/><p>3D is unavailable on this device. Your artwork remains editable below.</p></div>;return <div className="case-scene" aria-label="Interactive 3D case preview">{supported===null?<p className="scene-loading">Preparing your case…</p>:supported?<SceneBoundary key={props.design.device} fallback={fail}><Canvas camera={{position:[0,0,10],fov:42}} dpr={[1,1.6]} gl={{antialias:true,preserveDrawingBuffer:true,alpha:true}}><ambientLight intensity={1.5}/><directionalLight position={[-5,6,8]} intensity={3}/><directionalLight position={[5,0,3]} intensity={1.5}/><Suspense fallback={<Html center>Loading case…</Html>}><Case {...props}/></Suspense><OrbitControls makeDefault enablePan={false} enableRotate={!props.editing} enableZoom={!props.editing} minDistance={6} maxDistance={15}/><CameraView view={props.view||'Front'} editing={!!props.editing}/><ContactShadows position={[0,-3.18,0]} opacity={.25} scale={14} blur={3} far={5}/><Capture onCapture={props.onCapture}/></Canvas></SceneBoundary>:fail}</div>}
