'use client';
import {createContext,useContext,useState,useEffect,useRef,ReactNode} from 'react';
import {Product,products,Clan,defaultDevice,Design,searchProducts} from '@/lib/catalog';
import {Membership,emptyMembership} from '@/lib/membership';
import {designIdentity} from '@/lib/cart';
import {CustomerProfile,PaymentMethod,PaymentStatus,SavedAddress,ShippingAddress,OrderStatus,shippingFor,discountFor,codFeeFor} from '@/lib/commerce';
import {AdminData,applyAdminCatalog,defaultAdminData,normalizeAdminData,productPrice} from '@/lib/admin';
import {fetchRemoteCatalog,fetchRemoteAdminCatalog} from '@/lib/supabase/catalog-runtime';
import {saveRemoteAdminData} from '@/lib/supabase/admin-catalog';
import {loadRemoteAccount} from '@/lib/supabase/account';
import {loadRemoteAdminOrders,saveRemoteManualFulfilment} from '@/lib/supabase/admin-orders';
import {isAdminRole} from '@/lib/auth';
import {isConfirmedOrder} from '@/lib/payment-state';
import {useAuth} from './AuthProvider';
export type BagItem={key:string;productId:string;device:string;color:string;quantity:number;type?:'custom-case'|'ready-design';createdAt?:string;fixedDesignId?:string;design?:Design;productName?:string;unitPrice?:number};
export type StatusHistoryItem={status:string;at:string};
export type Order={id:string;databaseId?:string;date:string;items:BagItem[];subtotal:number;shipping:number;discount:number;codFee:number;total:number;clans:Clan[];customer:CustomerProfile;shippingAddress:ShippingAddress;paymentMethod:PaymentMethod;paymentStatus:PaymentStatus;status:OrderStatus|'New'|'Pending'|'Payment Pending'|'Payment Review'|'Processing'|'Printing'|'Cancelled'|'On Hold'|'Refunded';paymentProvider?:'razorpay'|'cod';razorpayOrderId?:string;razorpayPaymentId?:string;expectedAmount?:number;receivedAmount?:number;signatureVerified?:boolean;paymentVerifiedAt?:string;fulfilmentProvider?:string;qikinkOrderId?:string;fulfilmentStatus?:string;shipmentStatus?:string;courier?:string;trackingId?:string;trackingUrl?:string;statusHistory?:StatusHistoryItem[];estimatedDelivery?:string;adminNote?:string};
type State={bag:BagItem[];wishlist:string[];membership:Membership;orders:Order[];profile:CustomerProfile;addresses:SavedAddress[];subscribed:boolean;selectedDevice:string};
export type CheckoutInput={customer:CustomerProfile;shippingAddress:ShippingAddress;paymentMethod:PaymentMethod};
const blankProfile:CustomerProfile={name:'',email:'',phone:'',address:''};
const initial:State={bag:[],wishlist:[],membership:emptyMembership,orders:[],profile:blankProfile,addresses:[],subscribed:false,selectedDevice:''};
type PersistedOrder={id:string;databaseId?:string;total?:number;subtotal?:number;shipping?:number;discount?:number;codFee?:number;status?:string;paymentStatus?:string};
type Store=State&{ready:boolean;drawer:boolean;setDrawer:(v:boolean)=>void;searchOpen:boolean;setSearchOpen:(v:boolean)=>void;notice:string;notify:(v:string)=>void;adminData:AdminData;saveAdminData:(data:AdminData)=>Promise<void>;updateOrder:(id:string,patch:Partial<Order>)=>Promise<void>;patchOrder:(id:string,patch:Partial<Order>)=>void;setSelectedDevice:(device:string)=>void;add:(p:Product,device?:string,color?:string,design?:Design,quantity?:number)=>void;quantity:(key:string,n:number)=>void;toggleWish:(id:string)=>void;checkout:(input:CheckoutInput,persisted?:PersistedOrder)=>Order|null;saveProfile:(p:CustomerProfile)=>void;saveAddress:(a:SavedAddress)=>void;removeAddress:(id:string)=>void;setDefaultAddress:(id:string)=>void;subscribe:()=>void};
const Context=createContext<Store|null>(null);
export function useStore(){const s=useContext(Context);if(!s)throw new Error('Missing StoreProvider');return s;}
function migrateOrder(order:Partial<Order>&{id:string;date:string;items:BagItem[];total:number}):Order{const address=order.shippingAddress||{line1:'',line2:'',landmark:'',city:'',state:'',pin:''};return {...order,subtotal:order.subtotal??order.total,shipping:order.shipping??0,discount:order.discount??0,codFee:order.codFee??0,clans:order.clans||[],customer:order.customer||blankProfile,shippingAddress:address,paymentMethod:order.paymentMethod||'Online Payment',paymentStatus:order.paymentStatus||'Not processed',status:order.status||'Order Placed'} as Order}
export default function StoreProvider({children}:{children:ReactNode}){
 const auth=useAuth();
 const [state,setState]=useState<State>(initial),[adminData,setAdminData]=useState<AdminData>(defaultAdminData),[ready,setReady]=useState(false),[drawer,setDrawer]=useState(false),[searchOpen,setSearchOpen]=useState(false),[notice,setNotice]=useState('');const ref=useRef(state),adminRef=useRef(adminData);ref.current=state;adminRef.current=adminData;
 useEffect(()=>{let active=true;let localAdmin=defaultAdminData();try{localAdmin=normalizeAdminData(JSON.parse(localStorage.getItem('caseclan-admin-v1')||'null'));applyAdminCatalog(localAdmin);setAdminData(localAdmin);const saved=JSON.parse(localStorage.getItem('caseclan-store-v1')||'null');if(saved&&Array.isArray(saved.bag)&&Array.isArray(saved.wishlist)&&Array.isArray(saved.orders)&&saved.membership&&saved.profile){const bag=saved.bag.filter((item:BagItem)=>typeof item.productId==='string'&&typeof item.device==='string'&&Number.isInteger(item.quantity)&&item.quantity>0&&item.quantity<=10);setState({...initial,...saved,profile:{...blankProfile,...saved.profile},addresses:Array.isArray(saved.addresses)?saved.addresses:[],orders:[],selectedDevice:typeof saved.selectedDevice==='string'?saved.selectedDevice:'',bag,wishlist:saved.wishlist.filter((id:unknown)=>typeof id==='string')})}}catch{}document.documentElement.dataset.catalogSource='local-fallback';setReady(true);void fetchRemoteCatalog(localAdmin).then(remote=>{if(!active||!remote)return;applyAdminCatalog(remote);document.documentElement.dataset.catalogSource='supabase';setAdminData(remote);adminRef.current=remote;setState(current=>({...current,bag:current.bag.filter(item=>remote.products.some(product=>product.id===item.productId&&product.devices.includes(item.device))),wishlist:current.wishlist.filter(id=>remote.products.some(product=>product.id===id)),selectedDevice:remote.devices.some(device=>device.slug===current.selectedDevice)?current.selectedDevice:''}))}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('caseclan-store-v1',JSON.stringify(state))}catch{setNotice('Browser storage is unavailable. Changes will last for this visit.')}},[state,ready]);
 useEffect(()=>{if(!ready||!auth.user)return;let active=true;if(isAdminRole(auth.customer?.role)){void Promise.all([loadRemoteAdminOrders(),fetchRemoteAdminCatalog(adminRef.current)]).then(([orders,catalog])=>{if(!active)return;applyAdminCatalog(catalog);setAdminData(catalog);setState(current=>({...current,orders}))}).catch(()=>setNotice('Admin data could not be refreshed from Supabase.'))}else{void loadRemoteAccount(auth.user.id).then(remote=>{if(!active)return;setState(current=>({...current,profile:remote.customer,addresses:remote.addresses,orders:remote.orders}))}).catch(()=>setNotice('Your account is signed in, but saved account data could not be refreshed.'))}return()=>{active=false}},[ready,auth.user,auth.customer?.role]);
 useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id)}},[notice]);
 const saveAdminData=async(data:AdminData)=>{const normalized=normalizeAdminData(data);try{await saveRemoteAdminData(normalized,adminRef.current);const remote=await fetchRemoteAdminCatalog(normalized);applyAdminCatalog(remote);setAdminData(remote);adminRef.current=remote;try{localStorage.setItem('caseclan-admin-v1',JSON.stringify(remote))}catch{}setState(s=>({...s,bag:s.bag.filter(item=>remote.products.some(product=>product.id===item.productId))}));setNotice('Admin changes saved to Supabase.')}catch(error){const message=error instanceof Error?error.message:'Admin changes could not be saved.';setNotice(message);throw error}};
 const add=(p:Product,device=ref.current.selectedDevice||defaultDevice(p),color=p.colors[0],design?:Design,requestedQuantity=1)=>{if(p.status==='archived'||p.status==='draft'||!p.devices.includes(device)||!p.colors.includes(color)||adminRef.current.devices.find(item=>item.slug===device)?.available===false)return;if(p.kind==='custom'&&!design?.customization?.layers.length)return;const amount=Math.max(1,Math.min(10,Math.round(requestedQuantity))),existing=ref.current.bag.find(i=>i.productId===p.id&&i.device===device&&i.color===color&&designIdentity(i.design)===designIdentity(design));const key=existing?.key||crypto.randomUUID(),unitPrice=productPrice(p,device);setState(s=>({...s,selectedDevice:device,bag:s.bag.some(i=>i.key===key)?s.bag.map(i=>i.key===key?{...i,quantity:Math.min(10,i.quantity+amount)}:i):[...s.bag,{key,productId:p.id,device,color,quantity:amount,type:p.kind==='custom'?'custom-case':'ready-design',createdAt:new Date().toISOString(),fixedDesignId:p.kind==='ready'?p.id:undefined,design,productName:p.name,unitPrice}]}));setDrawer(true)};
 const checkout=(input:CheckoutInput,persisted?:PersistedOrder)=>{const s=ref.current;if(!s.bag.length||!persisted?.databaseId||!isConfirmedOrder(persisted))return null;const subtotal=persisted?.subtotal??s.bag.reduce((n,x)=>n+(x.unitPrice??adminRef.current.products.find(p=>p.id===x.productId)?.price??0)*x.quantity,0),settings=adminRef.current.settings,shipping=persisted?.shipping??(subtotal>=settings.freeShippingThreshold?0:settings.shippingCharge),discount=persisted?.discount??discountFor(),codFee=persisted?.codFee??(input.paymentMethod==='Cash on Delivery'?settings.codFee:0);const order:Order={id:persisted?.id||'CC-'+crypto.randomUUID().slice(0,8).toUpperCase(),databaseId:persisted?.databaseId,date:new Date().toISOString(),items:s.bag.map(x=>({...x})),subtotal,shipping,discount,codFee,total:persisted?.total??subtotal+shipping-discount+codFee,clans:[],customer:input.customer,shippingAddress:input.shippingAddress,paymentMethod:input.paymentMethod,paymentStatus:(persisted?.paymentStatus||'Not processed') as PaymentStatus,status:(persisted?.status||'Order Placed') as Order['status']};const profile={...input.customer,address:[input.shippingAddress.line1,input.shippingAddress.line2,input.shippingAddress.city,input.shippingAddress.state,input.shippingAddress.pin].filter(Boolean).join(', ')};const next={...s,profile,bag:[],orders:[order,...s.orders.filter(existing=>existing.id!==order.id)],membership:s.membership};ref.current=next;setState(next);setDrawer(false);return order};
 useEffect(()=>{type ToolContext={registerTool:(tool:object,options:object)=>Promise<void>|void};const context=(document as Document&{modelContext?:ToolContext}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'search_caseclan_catalog',description:'Read the CASECLAN concept catalog by product, personalization style or compatible phone. Does not purchase.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof(input as {query?:unknown}).query!=='string')throw new Error('query must be a string');return searchProducts((input as {query:string}).query).map(p=>({id:p.id,name:p.name,price:p.price,style:p.style,devices:p.devices}))}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
 const saveAddress=(address:SavedAddress)=>setState(s=>({...s,addresses:[...s.addresses.filter(a=>a.id!==address.id).map(a=>address.isDefault?{...a,isDefault:false}:a),address]}));
 const updateOrder=async(id:string,patch:Partial<Order>)=>{const order=ref.current.orders.find(item=>item.id===id);if(!order)return;try{const saved=order.databaseId?await saveRemoteManualFulfilment(order,patch):patch;setState(s=>({...s,orders:s.orders.map(item=>item.id===id?{...item,...saved}:item)}));setNotice('Fulfilment details saved.')}catch(error){setNotice(error instanceof Error?error.message:'Fulfilment details could not be saved.');throw error}};
 return <Context.Provider value={{...state,ready,drawer,setDrawer,searchOpen,setSearchOpen,notice,notify:setNotice,adminData,saveAdminData,updateOrder,patchOrder:(id,patch)=>setState(s=>({...s,orders:s.orders.map(item=>item.id===id?{...item,...patch}:item)})),setSelectedDevice:device=>{if(adminRef.current.devices.some(item=>item.slug===device&&item.active!==false&&item.available!==false))setState(s=>s.selectedDevice===device?s:{...s,selectedDevice:device})},add,quantity:(key,n)=>setState(s=>({...s,bag:n<=0?s.bag.filter(i=>i.key!==key):s.bag.map(i=>i.key===key?{...i,quantity:Math.min(10,n)}:i)})),toggleWish:id=>setState(s=>({...s,wishlist:s.wishlist.includes(id)?s.wishlist.filter(x=>x!==id):[...s.wishlist,id]})),checkout,saveProfile:profile=>setState(s=>({...s,profile})),saveAddress,removeAddress:id=>setState(s=>({...s,addresses:s.addresses.filter(a=>a.id!==id)})),setDefaultAddress:id=>setState(s=>({...s,addresses:s.addresses.map(a=>({...a,isDefault:a.id===id}))})),subscribe:()=>setState(s=>({...s,subscribed:true}))}}>{children}{notice&&<div role="status" className="toast">{notice}</div>}</Context.Provider>
}
