'use client';
import {createContext,useContext,useState,useEffect,useRef,ReactNode} from 'react';
import {Product,products,Clan,defaultDevice} from '@/lib/catalog';
import {Membership,emptyMembership,awardMembership} from '@/lib/membership';
export type BagItem={key:string;productId:string;device:string;color:string;quantity:number};
export type Order={id:string;date:string;items:BagItem[];total:number;clans:Clan[]};
type State={bag:BagItem[];wishlist:string[];membership:Membership;orders:Order[];profile:{name:string;email:string;address:string};subscribed:boolean};
const initial:State={bag:[],wishlist:[],membership:emptyMembership,orders:[],profile:{name:'',email:'',address:''},subscribed:false};
type Store=State&{ready:boolean;drawer:boolean;setDrawer:(v:boolean)=>void;searchOpen:boolean;setSearchOpen:(v:boolean)=>void;notice:string;notify:(v:string)=>void;add:(p:Product,device?:string,color?:string)=>void;quantity:(key:string,n:number)=>void;toggleWish:(id:string)=>void;checkout:(profile:State['profile'])=>Order|null;saveProfile:(p:State['profile'])=>void;subscribe:()=>void};
const Context=createContext<Store|null>(null);
export function useStore(){const s=useContext(Context);if(!s)throw new Error('Missing StoreProvider');return s;}
export default function StoreProvider({children}:{children:ReactNode}){
 const [state,setState]=useState<State>(initial),[ready,setReady]=useState(false),[drawer,setDrawer]=useState(false),[searchOpen,setSearchOpen]=useState(false),[notice,setNotice]=useState('');const ref=useRef(state);ref.current=state;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('caseclan-store-v1')||'null');if(saved&&Array.isArray(saved.bag)&&Array.isArray(saved.wishlist)&&Array.isArray(saved.orders)&&saved.membership&&saved.profile){setState({...initial,...saved,bag:saved.bag.filter((x:BagItem)=>products.some(p=>p.id===x.productId&&p.devices.includes(x.device)&&p.colors.includes(x.color))&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=10),wishlist:saved.wishlist.filter((id:string)=>products.some(p=>p.id===id))})}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('caseclan-store-v1',JSON.stringify(state))}catch{setNotice('Browser storage is unavailable. Changes will last for this visit.')}},[state,ready]);
 useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id)}},[notice]);
 const add=(p:Product,device=defaultDevice(p),color=p.colors[0])=>{if(!p.devices.includes(device)||!p.colors.includes(color))return;const key=`${p.id}:${device}:${color}`;setState(s=>({...s,bag:s.bag.some(i=>i.key===key)?s.bag.map(i=>i.key===key?{...i,quantity:Math.min(10,i.quantity+1)}:i):[...s.bag,{key,productId:p.id,device,color,quantity:1}]}));setDrawer(true)};
 const checkout=(profile:State['profile'])=>{const s=ref.current;if(!s.bag.length)return null;const order:Order={id:'CC-'+crypto.randomUUID().slice(0,8).toUpperCase(),date:new Date().toISOString(),items:s.bag.map(x=>({...x})),total:s.bag.reduce((n,x)=>n+products.find(p=>p.id===x.productId)!.price*x.quantity,0),clans:[...new Set(s.bag.map(x=>products.find(p=>p.id===x.productId)!.clan))]};const memberNumber=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const next={...s,profile,bag:[],orders:[order,...s.orders],membership:awardMembership(s.membership,{orderId:order.id,status:'paid',clans:order.clans,memberNumber,year:new Date().getFullYear()})};ref.current=next;setState(next);setDrawer(false);return order;};
 useEffect(()=>{type ToolContext={registerTool:(tool:object,options:object)=>Promise<void>|void};const context=(document as Document&{modelContext?:ToolContext}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'search_caseclan_catalog',description:'Read the CASECLAN concept catalog by product, clan or compatible phone. Does not purchase.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof(input as {query?:unknown}).query!=='string')throw new Error('query must be a string');const q=(input as {query:string}).query.toLowerCase();return products.filter(p=>`${p.name} ${p.clan} ${p.collection} ${p.devices.join(' ')}`.toLowerCase().includes(q.replaceAll(' ','-'))||`${p.name} ${p.clan} ${p.collection}`.toLowerCase().includes(q)).map(p=>({id:p.id,name:p.name,price:p.price,clan:p.clan,devices:p.devices}))}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
 return <Context.Provider value={{...state,ready,drawer,setDrawer,searchOpen,setSearchOpen,notice,notify:setNotice,add,quantity:(key,n)=>setState(s=>({...s,bag:n<=0?s.bag.filter(i=>i.key!==key):s.bag.map(i=>i.key===key?{...i,quantity:Math.min(10,n)}:i)})),toggleWish:id=>setState(s=>({...s,wishlist:s.wishlist.includes(id)?s.wishlist.filter(x=>x!==id):[...s.wishlist,id]})),checkout,saveProfile:profile=>setState(s=>({...s,profile})),subscribe:()=>setState(s=>({...s,subscribed:true}))}}>{children}{notice&&<div role="status" className="toast">{notice}</div>}</Context.Provider>
}
