'use client';
import Link from 'next/link';
import DesignFiles from './DesignFiles';
import {useState,useEffect} from 'react';
import {ArrowRight,Minus,Plus,Trash2,Search,ShoppingBag} from 'lucide-react';
import {useStore} from './StoreProvider';
import {products,productImage,deviceName,money,searchProducts} from '@/lib/catalog';
import ProductCard from './ProductCard';
export function CartPage(){const s=useStore();const total=s.bag.reduce((n,i)=>n+(products.find(p=>p.id===i.productId)?.price||0)*i.quantity,0);return <><div className="page-intro"><p className="eyebrow">YOUR PERSONAL SELECTION</p><h1>Your Cart</h1><p>Review every case, model and custom preview before checkout.</p></div>{s.bag.length?<section className="cart-page"><div>{s.bag.map(i=>{const p=products.find(p=>p.id===i.productId);if(!p)return null;return <article className="cart-row" key={i.key}><Link href={p.kind==='ready'?`/product/${p.id}/?device=${i.device}`:'/customize/?device='+i.device}><img src={i.design?.preview||i.design?.upload||productImage(p,i.device)} alt={i.design?.preview?'Custom design preview':p.name}/></Link><div><span className="eyebrow">{p.kind==='custom'?'CUSTOM CASE':'READY DESIGN'}</span><h2>{p.name}</h2><p>Phone model: {deviceName(i.device)}<br/>Finish: {i.color}</p>{p.kind==='custom'&&<p className="design-summary">One-of-one customization{i.design?.instructions&&<><br/>{i.design.instructions}</>}</p>}{i.design?.artifactId&&<DesignFiles id={i.design.artifactId}/>}<div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} onClick={()=>s.quantity(i.key,i.quantity-1)}><Minus size={14}/></button><span>{i.quantity}</span><button disabled={i.quantity>=10} aria-label={`Increase ${p.name} quantity`} onClick={()=>s.quantity(i.key,i.quantity+1)}><Plus size={14}/></button></div></div><div className="cart-row-end"><strong>{money(p.price*i.quantity)}</strong><button aria-label={`Remove ${p.name}`} onClick={()=>s.quantity(i.key,0)}><Trash2 size={18}/></button></div></article>})}</div><aside className="checkout-summary"><h2>Order Summary</h2><div className="summary-totals"><p><span>Subtotal</span><strong>{money(total)}</strong></p><p><span>Discount</span><span>—</span></p><p><span>Shipping</span><span>{total>=999?'Complimentary':'Calculated at checkout'}</span></p><p><strong>Total</strong><strong>{money(total)}</strong></p></div><Link href="/checkout/" className="button wide">PROCEED TO CHECKOUT <ArrowRight size={15}/></Link><Link href="/shop/" className="button outline wide">CONTINUE SHOPPING</Link></aside></section>:<section className="empty-state"><ShoppingBag size={36} strokeWidth={1}/><h3>Your cart is empty</h3><p>Discover a fixed ready design or begin with a blank custom case.</p><Link className="button" href="/shop/">SHOP CASES <ArrowRight size={15}/></Link></section>}</>}
export function SearchPage(){const[q,setQ]=useState('');useEffect(()=>setQ(new URLSearchParams(window.location.search).get('q')||''),[]);const found=q.trim()?searchProducts(q):products.filter(p=>p.kind==='ready');const update=(value:string)=>{setQ(value);const url=value?`/search/?q=${encodeURIComponent(value)}`:'/search/';history.replaceState(null,'',url)};return <><div className="page-intro"><p className="eyebrow">FIND YOUR OWN EXPRESSION</p><h1>{q?`Search results for “${q}”`:'Search CASECLAN'}</h1><p>Search by product, design, phone model or category.</p><div className="search-field"><Search size={20}/><input aria-label="Search designs" placeholder="Try iPhone 17 or Word Cloud" value={q} onChange={e=>update(e.target.value)}/>{q&&<button className="text-link" onClick={()=>update('')}>Clear</button>}</div></div><section className="shop-content"><p className="small muted">{found.length} {found.length===1?'result':'results'}</p><div className="shop-grid">{found.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!found.length&&<div className="empty-state"><h3>No results found.</h3><p>Try a product name, phone model, design style or category.</p><button className="button" onClick={()=>update('')}>CLEAR SEARCH</button></div>}</section></>}
