'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ArrowRight,Minus,Plus,Trash2,Search} from 'lucide-react';
import {useStore} from './StoreProvider';
import {products,productImage,deviceName,money,searchProducts} from '@/lib/catalog';
import ProductCard from './ProductCard';
export function CartPage(){const s=useStore();const total=s.bag.reduce((n,i)=>n+(products.find(p=>p.id===i.productId)?.price||0)*i.quantity,0);return <><div className="page-intro"><p className="eyebrow">YOUR PERSONAL SELECTION</p><h1>Your Cart</h1><p>Review your phone model and design before checkout.</p></div>{s.bag.length?<section className="cart-page"><div>{s.bag.map(i=>{const p=products.find(p=>p.id===i.productId);if(!p)return null;return <article className="cart-row" key={i.key}><Link href={`/product/${p.id}/?device=${i.device}`}><img src={i.design?.upload||productImage(p,i.device)} alt={i.design?.upload?'Your uploaded artwork':p.name}/></Link><div><Link href={`/product/${p.id}/?device=${i.device}`}><h2>{p.name}</h2></Link><p>{deviceName(i.device)} · {i.color}</p>{i.design&&<p className="design-summary">{i.design.upload?i.design.filename:`“${i.design.name}” · ${i.design.font} · ${i.design.textColor}`}<br/>{i.design.style}{i.design.instructions&&<><br/>{i.design.instructions}</>}</p>}<div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} onClick={()=>s.quantity(i.key,i.quantity-1)}><Minus size={14}/></button><span>{i.quantity}</span><button disabled={i.quantity>=10} aria-label={`Increase ${p.name} quantity`} onClick={()=>s.quantity(i.key,i.quantity+1)}><Plus size={14}/></button></div></div><div className="cart-row-end"><strong>{money(p.price*i.quantity)}</strong><button aria-label={`Remove ${p.name}`} onClick={()=>s.quantity(i.key,0)}><Trash2 size={18}/></button></div></article>})}</div><aside className="checkout-summary"><h2>Your Order</h2><div className="summary-totals"><p><span>Subtotal</span><strong>{money(total)}</strong></p><p><span>Shipping</span><span>{total>=999?'Complimentary':money(999-total)+' to free shipping'}</span></p><p><strong>Total</strong><strong>{money(total)}</strong></p></div><Link href="/checkout/" className="button wide">SECURE CHECKOUT <ArrowRight size={15}/></Link><p className="payment-note">Demo checkout · No payment collected</p><Link href="/shop/" className="text-link">Continue browsing <ArrowRight size={14}/></Link></aside></section>:<section className="empty-state"><h3>Your cart is waiting.</h3><p>Choose a ready design or create a case with your name.</p><Link className="button" href="/shop/">EXPLORE OUR DESIGNS <ArrowRight size={15}/></Link></section>}</>}
export function SearchPage(){const[q,setQ]=useState('');useEffect(()=>setQ(new URLSearchParams(window.location.search).get('q')||''),[]);const found=q.trim()?searchProducts(q):products;return <><div className="page-intro"><p className="eyebrow">FIND YOUR OWN EXPRESSION</p><h1>Search CASECLAN</h1><p>Search by design, phone model or personalization style.</p><div className="search-field"><Search size={20}/><input aria-label="Search designs" placeholder="Try iPhone 17 or Word Cloud" value={q} onChange={e=>setQ(e.target.value)}/></div></div><section className="shop-content"><p className="small muted">{found.length} designs</p><div className="shop-grid">{found.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!found.length&&<div className="empty-state"><h3>No designs found.</h3><button className="button" onClick={()=>setQ('')}>SHOW ALL DESIGNS</button></div>}</section></>}
