import {modelConfig} from './mockups.ts';
export {modelConfig} from './mockups.ts';
export type {CameraLayout,ModelConfig} from './mockups.ts';
export type Layer={id:string;type:'text'|'image';text:string;src?:string;originalSrc?:string;sourceWidth?:number;sourceHeight?:number;font:string;color:string;x:number;y:number;width:number;height:number;rotation:number;locked?:boolean;placeholderId?:string;minFontSize?:number};
export type Customization={version:1;device:string;name:string;color:string;background:string;layers:Layer[];instructions:string};
export const fonts:Record<string,string>={Editorial:'Georgia, serif',Modern:'Arial, sans-serif',Signature:'cursive',Bold:'Impact, Arial Black, sans-serif'};
export const initialCustomization:Customization={version:1,device:'iphone-17-pro',name:'Custom artwork',color:'#17191a',background:'transparent',layers:[],instructions:''};
export function textLayer(text:string,x=500,y=1100,font='Modern',color='#17191a',width=650,height=170):Layer{return {id:crypto.randomUUID(),type:'text',text,font,color,x,y,width,height,rotation:0}}
export function layerBounds(l:Layer){const a=l.rotation*Math.PI/180;return {w:Math.abs(l.width*Math.cos(a))+Math.abs(l.height*Math.sin(a)),h:Math.abs(l.width*Math.sin(a))+Math.abs(l.height*Math.cos(a))}}
export function printRect(device:string){const p=modelConfig(device).printArea;return {x:p.x*1000,y:p.y*2000,width:p.width*1000,height:p.height*2000}}
export function imageMinimumSize(layer:Pick<Layer,'sourceWidth'|'sourceHeight'|'rotation'>,device:string){const sourceWidth=Math.max(1,layer.sourceWidth||1),sourceHeight=Math.max(1,layer.sourceHeight||1),p=printRect(device),a=(layer.rotation||0)*Math.PI/180,requiredWidth=p.width*Math.abs(Math.cos(a))+p.height*Math.abs(Math.sin(a)),requiredHeight=p.width*Math.abs(Math.sin(a))+p.height*Math.abs(Math.cos(a)),scale=Math.max(requiredWidth/sourceWidth,requiredHeight/sourceHeight);return {width:sourceWidth*scale,height:sourceHeight*scale,scale}}
function constrainImageLayer(layer:Layer,device:string):Layer{const sourceWidth=Math.max(1,layer.sourceWidth||layer.width),sourceHeight=Math.max(1,layer.sourceHeight||layer.height),minimum=imageMinimumSize({...layer,sourceWidth,sourceHeight},device),requestedScale=Math.max(layer.width/sourceWidth,layer.height/sourceHeight,minimum.scale),scale=Math.min(requestedScale,minimum.scale*6),width=sourceWidth*scale,height=sourceHeight*scale,p=printRect(device),a=layer.rotation*Math.PI/180,cos=Math.cos(a),sin=Math.sin(a),corners=[[p.x,p.y],[p.x+p.width,p.y],[p.x,p.y+p.height],[p.x+p.width,p.y+p.height]],u=corners.map(([x,y])=>cos*x+sin*y),v=corners.map(([x,y])=>-sin*x+cos*y),minU=Math.max(...u)-width/2,maxU=Math.min(...u)+width/2,minV=Math.max(...v)-height/2,maxV=Math.min(...v)+height/2,currentU=cos*layer.x+sin*layer.y,currentV=-sin*layer.x+cos*layer.y,centerU=Math.max(minU,Math.min(maxU,currentU)),centerV=Math.max(minV,Math.min(maxV,currentV));return {...layer,sourceWidth,sourceHeight,width,height,x:cos*centerU-sin*centerV,y:sin*centerU+cos*centerV}}
export function fitImageLayer(layer:Layer,device:string):Layer{const p=printRect(device),base={...layer,rotation:0,x:p.x+p.width/2,y:p.y+p.height/2},minimum=imageMinimumSize(base,device);return constrainImageLayer({...base,width:minimum.width,height:minimum.height},device)}
export function centerImageLayer(layer:Layer,device:string):Layer{const p=printRect(device);return constrainImageLayer({...layer,x:p.x+p.width/2,y:p.y+p.height/2},device)}
export function imageZoomPercent(layer:Layer,device:string){const minimum=imageMinimumSize(layer,device);return Math.round(Math.max(layer.width/minimum.width,layer.height/minimum.height)*100)}
export function resizeImageLayer(layer:Layer,device:string,percent:number):Layer{const minimum=imageMinimumSize(layer,device),factor=Math.max(1,Math.min(6,percent/100));return constrainImageLayer({...layer,width:minimum.width*factor,height:minimum.height*factor},device)}
export function imageEffectivePpi(layer:Layer,device:string){const c=modelConfig(device);if(!layer.sourceWidth||!layer.sourceHeight)return 0;const printedWidth=layer.width/1000*c.width,printedHeight=layer.height/2000*c.height;return Math.round(Math.min(layer.sourceWidth/printedWidth,layer.sourceHeight/printedHeight))}
export function printExportSize(device:string,dpi=720){const c=modelConfig(device),width=Math.max(1200,Math.round(c.width*dpi));return {width,height:width*2,dpi}}
export function constrainLayer(layer:Layer,device:string):Layer{if(layer.type==='image')return constrainImageLayer(layer,device);const c=modelConfig(device),s=c.safe,r=c.camera;let l={...layer,width:Math.max(60,Math.min(870,layer.width)),height:Math.max(40,Math.min(1250,layer.height))};let b=layerBounds(l);const scale=Math.min(1,(1000-2*s)/b.w,(2000-2*s-r.y-r.height)/b.h);l={...l,width:l.width*scale,height:l.height*scale};b=layerBounds(l);l.x=Math.max(s+b.w/2,Math.min(1000-s-b.w/2,l.x));l.y=Math.max(s+b.h/2,Math.min(2000-s-b.h/2,l.y));if(l.x+b.w/2>r.x-s&&l.x-b.w/2<r.x+r.width+s&&l.y+b.h/2>r.y-s&&l.y-b.h/2<r.y+r.height+s)l.y=r.y+r.height+s+b.h/2;return l}
export function hitLayer(layers:Layer[],x:number,y:number){return [...layers].reverse().find(l=>{const a=-l.rotation*Math.PI/180,dx=x-l.x,dy=y-l.y;return Math.abs(dx*Math.cos(a)-dy*Math.sin(a))<=l.width/2&&Math.abs(dx*Math.sin(a)+dy*Math.cos(a))<=l.height/2})}
const imageCache=new Map<string,Promise<HTMLImageElement>>();
function loadImage(src:string){if(!imageCache.has(src))imageCache.set(src,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src}));return imageCache.get(src)!}
function drawImageCover(ctx:CanvasRenderingContext2D,im:HTMLImageElement,width:number,height:number){const scale=Math.max(width/im.naturalWidth,height/im.naturalHeight),sourceWidth=width/scale,sourceHeight=height/scale,sourceX=(im.naturalWidth-sourceWidth)/2,sourceY=(im.naturalHeight-sourceHeight)/2;ctx.save();ctx.beginPath();ctx.rect(-width/2,-height/2,width,height);ctx.clip();ctx.drawImage(im,sourceX,sourceY,sourceWidth,sourceHeight,-width/2,-height/2,width,height);ctx.restore()}
export async function renderArtwork(d:Customization,width=1024,guides=false,selected?:string,useOriginal=false){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=width*2;const ctx=canvas.getContext('2d')!;ctx.scale(width/1000,width/1000);const c=modelConfig(d.device);ctx.beginPath();ctx.roundRect(0,0,1000,2000,c.cornerRadius);ctx.roundRect(c.camera.x,c.camera.y,c.camera.width,c.camera.height,65);ctx.clip('evenodd');if(d.background!=='transparent'){ctx.fillStyle=d.background;ctx.fillRect(0,0,1000,2000)}for(const l of d.layers){ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.rotation*Math.PI/180);if(l.type==='image'){const source=useOriginal&&l.originalSrc?l.originalSrc:l.src;if(source){try{const im=await loadImage(source);drawImageCover(ctx,im,l.width,l.height)}catch{}}else{ctx.fillStyle='rgba(255,255,255,.07)';ctx.fillRect(-l.width/2,-l.height/2,l.width,l.height);ctx.strokeStyle='rgba(255,255,255,.34)';ctx.lineWidth=5;ctx.setLineDash([18,14]);ctx.strokeRect(-l.width/2,-l.height/2,l.width,l.height);ctx.setLineDash([]);ctx.fillStyle='rgba(255,255,255,.62)';ctx.font='28px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l.text.toUpperCase(),0,0)}}else{ctx.fillStyle=l.color;let size=l.height*.82;ctx.font=`${l.font==='Bold'?'900':'400'} ${size}px ${fonts[l.font]||fonts.Modern}`;const measured=ctx.measureText(l.text).width;if(measured>l.width){size=Math.max(l.minFontSize||24,size*l.width/measured);ctx.font=`${l.font==='Bold'?'900':'400'} ${size}px ${fonts[l.font]||fonts.Modern}`;}ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l.text,0,0)}if(guides&&selected===l.id&&!l.locked){ctx.strokeStyle='#70c7f7';ctx.lineWidth=4;ctx.strokeRect(-l.width/2,-l.height/2,l.width,l.height);for(const [x,y] of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.fillStyle='#fff';ctx.fillRect(x*l.width/2-9,y*l.height/2-9,18,18)}}ctx.restore()}ctx.fillStyle=d.background==='transparent'||d.background==='#eee9df'?'#17191a':'#f3f3f1';ctx.font='28px Arial';ctx.textAlign='center';ctx.fillText('C A S E C L A N',500,1880);try{const mask=await loadImage(c.assets.printMask);ctx.save();ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0,1000,2000);ctx.restore()}catch{}if(guides){ctx.strokeStyle='#91bcb0';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.strokeRect(c.safe,c.safe,1000-2*c.safe,2000-2*c.safe);ctx.strokeRect(c.camera.x-10,c.camera.y-10,c.camera.width+20,c.camera.height+20)}return canvas}
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('caseclan-studio',1);r.onupgradeneeded=()=>r.result.createObjectStore('artifacts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function saveArtifact(key:string,value:unknown){const database=await db();try{await new Promise<void>((resolve,reject)=>{const tx=database.transaction('artifacts','readwrite');tx.objectStore('artifacts').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{database.close()}}
export async function readArtifact<T>(key:string){const database=await db();try{return await new Promise<T|undefined>((resolve,reject)=>{const r=database.transaction('artifacts').objectStore('artifacts').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{database.close()}}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
