import {buildTemplateLayers,defaultTemplateValues,templateForStyle} from './templates.ts';
export type Layer={id:string;type:'text'|'image';text:string;src?:string;font:string;color:string;x:number;y:number;width:number;height:number;rotation:number;locked?:boolean;placeholderId?:string;minFontSize?:number};
export type Customization={version:1;device:string;template:string;templateId?:string;name:string;color:string;background:string;layers:Layer[];instructions:string};
export type CameraLayout='dual-diagonal'|'dual-vertical'|'triple-square'|'triple-wide';
export type ModelConfig={url:string|null;printMesh:string;width:number;height:number;camera:{x:number;y:number;width:number;height:number};safe:number;development:boolean;cameraLayout:CameraLayout;cornerRadius:number};
/** Model units and UVs must be calibrated against approved production files before fulfillment. */
export const approvedModels:Record<string,ModelConfig>={};
export function modelConfig(device:string):ModelConfig{if(approvedModels[device])return approvedModels[device];const is17Pro=device.startsWith('iphone-17-pro'),vertical=device.startsWith('iphone-16')||device==='iphone-17',pro=device.includes('pro'),max=device.includes('max')||device.includes('plus');let cameraLayout:CameraLayout,camera:ModelConfig['camera'];if(is17Pro){cameraLayout='triple-wide';camera={x:48,y:55,width:904,height:440}}else if(pro){cameraLayout='triple-square';camera={x:62,y:58,width:500,height:510}}else if(vertical){cameraLayout='dual-vertical';camera={x:70,y:58,width:292,height:520}}else{cameraLayout='dual-diagonal';camera={x:64,y:58,width:420,height:455}}return {url:null,printMesh:'PrintSurface',width:max?2.96:2.8,height:max?6.05:5.8,camera,safe:70,development:false,cameraLayout,cornerRadius:max?106:112}}
export const fonts:Record<string,string>={Editorial:'Georgia, serif',Modern:'Arial, sans-serif',Signature:'cursive',Bold:'Impact, Arial Black, sans-serif'};
export const initialCustomization:Customization={version:1,device:'iphone-17-pro',template:'Minimal Name',name:'',color:'#ffffff',background:'#191a1b',layers:[],instructions:''};
export function textLayer(text:string,x=500,y=1100,font='Modern',color='#ffffff',width=650,height=170):Layer{return {id:crypto.randomUUID(),type:'text',text,font,color,x,y,width,height,rotation:0}}
export function templateLayers(name:string,template:string,color:string):Layer[]{if(template==='Photo Collage')return [];const definition=templateForStyle(template),values=defaultTemplateValues(definition),label=name.trim()||'YOUR NAME';for(const field of definition.editableLayers){if(field.type==='text'){values[field.id]=field.id==='initial'?label[0].toUpperCase():label}}return buildTemplateLayers(definition,values).map(layer=>layer.placeholderId&&layer.type==='text'?{...layer,color}:layer)}
export function layerBounds(l:Layer){const a=l.rotation*Math.PI/180;return {w:Math.abs(l.width*Math.cos(a))+Math.abs(l.height*Math.sin(a)),h:Math.abs(l.width*Math.sin(a))+Math.abs(l.height*Math.cos(a))}}
export function constrainLayer(layer:Layer,device:string):Layer{const c=modelConfig(device),s=c.safe,r=c.camera;let l={...layer,width:Math.max(60,Math.min(870,layer.width)),height:Math.max(40,Math.min(1250,layer.height))};let b=layerBounds(l);const scale=Math.min(1,(1000-2*s)/b.w,(2000-2*s-r.y-r.height)/b.h);l={...l,width:l.width*scale,height:l.height*scale};b=layerBounds(l);l.x=Math.max(s+b.w/2,Math.min(1000-s-b.w/2,l.x));l.y=Math.max(s+b.h/2,Math.min(2000-s-b.h/2,l.y));if(l.x+b.w/2>r.x-s&&l.x-b.w/2<r.x+r.width+s&&l.y+b.h/2>r.y-s&&l.y-b.h/2<r.y+r.height+s)l.y=r.y+r.height+s+b.h/2;return l}
export function hitLayer(layers:Layer[],x:number,y:number){return [...layers].reverse().find(l=>{const a=-l.rotation*Math.PI/180,dx=x-l.x,dy=y-l.y;return Math.abs(dx*Math.cos(a)-dy*Math.sin(a))<=l.width/2&&Math.abs(dx*Math.sin(a)+dy*Math.cos(a))<=l.height/2})}
const imageCache=new Map<string,Promise<HTMLImageElement>>();
function loadImage(src:string){if(!imageCache.has(src))imageCache.set(src,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src}));return imageCache.get(src)!}
function drawImageCover(ctx:CanvasRenderingContext2D,im:HTMLImageElement,width:number,height:number){const scale=Math.max(width/im.naturalWidth,height/im.naturalHeight),sourceWidth=width/scale,sourceHeight=height/scale,sourceX=(im.naturalWidth-sourceWidth)/2,sourceY=(im.naturalHeight-sourceHeight)/2;ctx.save();ctx.beginPath();ctx.rect(-width/2,-height/2,width,height);ctx.clip();ctx.drawImage(im,sourceX,sourceY,sourceWidth,sourceHeight,-width/2,-height/2,width,height);ctx.restore()}
export async function renderArtwork(d:Customization,width=1024,guides=false,selected?:string){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=width*2;const ctx=canvas.getContext('2d')!;ctx.scale(width/1000,width/1000);const c=modelConfig(d.device);ctx.beginPath();ctx.roundRect(0,0,1000,2000,100);ctx.roundRect(c.camera.x,c.camera.y,c.camera.width,c.camera.height,65);ctx.clip('evenodd');ctx.fillStyle=d.background;ctx.fillRect(0,0,1000,2000);for(const l of d.layers){ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.rotation*Math.PI/180);if(l.type==='image'){if(l.src){try{const im=await loadImage(l.src);drawImageCover(ctx,im,l.width,l.height)}catch{}}else{ctx.fillStyle='rgba(255,255,255,.07)';ctx.fillRect(-l.width/2,-l.height/2,l.width,l.height);ctx.strokeStyle='rgba(255,255,255,.34)';ctx.lineWidth=5;ctx.setLineDash([18,14]);ctx.strokeRect(-l.width/2,-l.height/2,l.width,l.height);ctx.setLineDash([]);ctx.fillStyle='rgba(255,255,255,.62)';ctx.font='28px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l.text.toUpperCase(),0,0)}}else{ctx.fillStyle=l.color;let size=l.height*.82;ctx.font=`${l.font==='Bold'?'900':'400'} ${size}px ${fonts[l.font]||fonts.Modern}`;const measured=ctx.measureText(l.text).width;if(measured>l.width){size=Math.max(l.minFontSize||24,size*l.width/measured);ctx.font=`${l.font==='Bold'?'900':'400'} ${size}px ${fonts[l.font]||fonts.Modern}`;}ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l.text,0,0)}if(guides&&selected===l.id&&!l.locked){ctx.strokeStyle='#70c7f7';ctx.lineWidth=4;ctx.strokeRect(-l.width/2,-l.height/2,l.width,l.height);for(const [x,y] of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.fillStyle='#fff';ctx.fillRect(x*l.width/2-9,y*l.height/2-9,18,18)}}ctx.restore()}ctx.fillStyle=d.background==='#eee9df'?'#111':'#ddd';ctx.font='28px Arial';ctx.textAlign='center';ctx.fillText('C A S E C L A N',500,1880);if(guides){ctx.strokeStyle='#91bcb0';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.strokeRect(c.safe,c.safe,1000-2*c.safe,2000-2*c.safe);ctx.strokeRect(c.camera.x-10,c.camera.y-10,c.camera.width+20,c.camera.height+20)}return canvas}
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('caseclan-studio',1);r.onupgradeneeded=()=>r.result.createObjectStore('artifacts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function saveArtifact(key:string,value:unknown){const database=await db();try{await new Promise<void>((resolve,reject)=>{const tx=database.transaction('artifacts','readwrite');tx.objectStore('artifacts').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{database.close()}}
export async function readArtifact<T>(key:string){const database=await db();try{return await new Promise<T|undefined>((resolve,reject)=>{const r=database.transaction('artifacts').objectStore('artifacts').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{database.close()}}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
