import {notFound} from 'next/navigation';
import {devices} from '@/lib/catalog';
import {CartPage,SearchPage} from '@/components/UtilityPages';
import Shop from '@/components/Shop';
import InfoPages from '@/components/InfoPages';
import Account,{Wishlist,Checkout,Login} from '@/components/Account';
import {AboutPage,FAQPage,PolicyPage,TrackOrderPage,ContactPage} from '@/components/CustomerPages';
const pages=['sustainability','careers','press','cart','search','personalized','ready-designs','custom-upload','coming-soon','shop','iphone','samsung','new-drops','devices','clans','collections','our-story','about','faq','faqs','size-guide','track-order','returns','returns-policy','shipping-policy','contact','privacy','privacy-policy','terms','wishlist','login','account','checkout'];
export function generateStaticParams(){return [...pages,...devices.map(d=>d.slug)].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const device=devices.find(d=>d.slug===slug);const title=device?`${device.name} Cases`:slug.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');return {title,description:`${title}. Discover CASECLAN premium phone cases and make it your own.`,openGraph:{title:`${title} | CASECLAN`,description:`Explore ${title.toLowerCase()} at CASECLAN.`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(devices.some(d=>d.slug===slug))return <Shop device={slug}/>;if(slug==='shop'||slug==='new-drops'||slug==='personalized'||slug==='collections'||slug==='ready-designs')return <Shop kind="ready"/>;if(slug==='cart')return <CartPage/>;if(slug==='search')return <SearchPage/>;if(slug==='iphone'||slug==='samsung')return <Shop brand={slug==='iphone'?'iPhone':'Samsung'}/>;if(slug==='custom-upload')return <InfoPages slug="design-your-own"/>;if(slug==='login')return <Login/>;if(slug==='account')return <Account/>;if(slug==='wishlist')return <Wishlist/>;if(slug==='checkout')return <Checkout/>;if(slug==='about'||slug==='our-story')return <AboutPage/>;if(slug==='faq'||slug==='faqs')return <FAQPage/>;if(slug==='track-order')return <TrackOrderPage/>;if(slug==='contact')return <ContactPage/>;if(slug==='shipping-policy'||slug==='returns-policy'||slug==='privacy-policy'||slug==='terms')return <PolicyPage slug={slug}/>;if(!pages.includes(slug))notFound();return <InfoPages slug={slug}/>}
