import{adminClient,cors,hmacHex,json,providerEntity,safeEqual}from'../_shared/razorpay.ts';

Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'Method not allowed.'},405);
 const raw=await req.text(),signature=req.headers.get('x-razorpay-signature')||'',secret=Deno.env.get('RAZORPAY_WEBHOOK_SECRET')||'';if(!secret)return json(req,{error:'Webhook secret is not configured.'},503);
 const expected=await hmacHex(secret,raw);if(!safeEqual(expected,signature))return json(req,{error:'Invalid webhook signature.'},401);
 try{
  const payload=JSON.parse(raw),eventType=String(payload.event||''),eventId=req.headers.get('x-razorpay-event-id')||await hmacHex(secret,raw),paymentEntity=providerEntity(payload,'payment'),orderEntity=providerEntity(payload,'order'),refundEntity=providerEntity(payload,'refund'),providerOrderId=String(paymentEntity.order_id||orderEntity.id||''),providerPaymentId=String(paymentEntity.id||refundEntity.payment_id||''),admin=adminClient();
  const{error:eventError}=await admin.schema('private').from('payment_events').insert({provider:'razorpay',provider_event_id:eventId,event_type:eventType,provider_order_id:providerOrderId||null,provider_payment_id:providerPaymentId||null,payload});if(eventError){if(eventError.code==='23505')return json(req,{ok:true,duplicate:true});throw eventError}
  if(!providerOrderId)return json(req,{ok:true,ignored:true});const{data:payment}=await admin.from('payments').select('*').eq('provider_order_id',providerOrderId).maybeSingle();if(!payment)return json(req,{ok:true,ignored:true});
  if((eventType==='payment.captured'||eventType==='order.paid')&&payment.status!=='paid'){
   const entity=Object.keys(paymentEntity).length?paymentEntity:orderEntity,received=Number(paymentEntity.amount||orderEntity.amount_paid||0),matches=received===Number(payment.expected_amount)&&String(entity.currency||payment.currency)===payment.currency;
   if(matches){const verifiedAt=new Date().toISOString();await admin.from('payments').update({provider_payment_id:providerPaymentId||payment.provider_payment_id,received_amount:received,status:'paid',payment_method:String(paymentEntity.method||payment.payment_method||''),signature_verified:true,verified_at:verifiedAt,metadata:{...(payment.metadata||{}),webhook_event:eventType}}).eq('id',payment.id);const{data:order}=await admin.from('orders').select('metadata').eq('id',payment.order_id).single();await admin.from('orders').update({payment_status:'paid',status:'Confirmed',metadata:{...(order?.metadata||{}),razorpay_order_id:providerOrderId,razorpay_payment_id:providerPaymentId,payment_verified_at:verifiedAt}}).eq('id',payment.order_id)}else{await admin.from('payments').update({provider_payment_id:providerPaymentId||null,received_amount:received,status:'amount_mismatch',metadata:{...(payment.metadata||{}),webhook_event:eventType}}).eq('id',payment.id);await admin.from('orders').update({payment_status:'amount_mismatch',status:'Payment Review'}).eq('id',payment.order_id)}
  }else if(eventType==='payment.failed'&&payment.status!=='paid'){await admin.from('payments').update({provider_payment_id:providerPaymentId||null,received_amount:Number(paymentEntity.amount||0),status:'failed',payment_method:String(paymentEntity.method||''),metadata:{...(payment.metadata||{}),webhook_event:eventType,error_code:paymentEntity.error_code||null,error_description:paymentEntity.error_description||null}}).eq('id',payment.id);await admin.from('orders').update({payment_status:'failed',status:'Payment Pending'}).eq('id',payment.order_id)
  }else if(eventType==='refund.processed'&&payment.status==='paid'){await admin.from('payments').update({status:'refunded',metadata:{...(payment.metadata||{}),webhook_event:eventType,refund_id:refundEntity.id||null}}).eq('id',payment.id);await admin.from('orders').update({payment_status:'refunded',status:'Refunded'}).eq('id',payment.order_id)}
  return json(req,{ok:true});
 }catch(error){return json(req,{error:error instanceof Error?error.message:'Webhook processing failed.'},500)}
});
