-- Prepared only. Do not apply until CASECLAN's Supabase project and secret-key
-- connection have both been verified.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke all on function private.set_updated_at() from public, anon, authenticated;

create table public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (char_length(btrim(name)) between 1 and 160),
  description text,
  short_description text,
  kind text not null check (kind in ('ready', 'custom')),
  status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
  price numeric(12,2) not null check (price >= 0),
  compare_at_price numeric(12,2) check (compare_at_price is null or compare_at_price >= 0),
  cost_price numeric(12,2) check (cost_price is null or cost_price >= 0),
  sku text unique,
  material text,
  collection text,
  artwork_locked boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  storage_path text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (product_id, storage_path)
);

create table public.phone_models (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  brand text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  display_order integer not null default 0,
  base_mockup_path text,
  case_overlay_path text,
  highlight_overlay_path text,
  shadow_overlay_path text,
  print_mask_path text,
  camera_mask_path text,
  print_area jsonb not null default '{}'::jsonb,
  safe_area jsonb not null default '{}'::jsonb,
  camera_exclusion jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_phone_models (
  product_id uuid not null references public.products(id) on delete cascade,
  phone_model_id uuid not null references public.phone_models(id) on delete cascade,
  sku text,
  price_override numeric(12,2) check (price_override is null or price_override >= 0),
  available boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (product_id, phone_model_id)
);

create table public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  full_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  label text,
  recipient_name text not null,
  phone text not null,
  line1 text not null,
  line2 text,
  landmark text,
  city text not null,
  state text not null,
  postal_code text not null,
  country_code text not null default 'IN' check (char_length(country_code) = 2),
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id) on delete set null,
  guest_email text,
  status text not null default 'new',
  payment_status text not null default 'not_processed',
  payment_method text,
  currency text not null default 'INR' check (char_length(currency) = 3),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  cod_fee numeric(12,2) not null default 0 check (cod_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  shipping_address jsonb not null,
  tracking_id text,
  courier text,
  admin_note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_email is not null)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  phone_model_id uuid references public.phone_models(id) on delete set null,
  product_name text not null,
  sku text,
  quantity integer not null check (quantity between 1 and 100),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  fixed_design_id text,
  item_type text not null check (item_type in ('ready-design', 'custom-case')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.customizations (
  id uuid primary key default gen_random_uuid(),
  order_item_id uuid not null unique references public.order_items(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  design_state jsonb not null,
  customer_upload_paths text[] not null default '{}',
  preview_path text,
  print_ready_path text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'hold', 'rejected', 'printed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null check (char_length(btrim(code)) between 2 and 64),
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  value numeric(12,2) not null check (value > 0),
  minimum_cart_value numeric(12,2) not null default 0 check (minimum_cart_value >= 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  usage_count integer not null default 0 check (usage_count >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (discount_type <> 'percentage' or value <= 100),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);
create unique index coupons_code_lower_idx on public.coupons (lower(code));

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  title text,
  body text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'hidden')),
  verified_purchase boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, customer_id)
);

create table public.store_settings (
  key text primary key,
  value jsonb not null,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index product_images_product_id_idx on public.product_images(product_id);
create index product_phone_models_phone_model_id_idx on public.product_phone_models(phone_model_id);
create index addresses_customer_id_idx on public.addresses(customer_id);
create unique index addresses_one_default_per_customer_idx on public.addresses(customer_id) where is_default;
create index orders_customer_id_created_at_idx on public.orders(customer_id, created_at desc);
create index orders_status_created_at_idx on public.orders(status, created_at desc);
create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_product_id_idx on public.order_items(product_id);
create index order_items_phone_model_id_idx on public.order_items(phone_model_id);
create index customizations_customer_id_idx on public.customizations(customer_id);
create index reviews_product_id_status_idx on public.reviews(product_id, status);
create index reviews_customer_id_idx on public.reviews(customer_id);

create trigger products_set_updated_at before update on public.products for each row execute function private.set_updated_at();
create trigger phone_models_set_updated_at before update on public.phone_models for each row execute function private.set_updated_at();
create trigger customers_set_updated_at before update on public.customers for each row execute function private.set_updated_at();
create trigger addresses_set_updated_at before update on public.addresses for each row execute function private.set_updated_at();
create trigger orders_set_updated_at before update on public.orders for each row execute function private.set_updated_at();
create trigger customizations_set_updated_at before update on public.customizations for each row execute function private.set_updated_at();
create trigger coupons_set_updated_at before update on public.coupons for each row execute function private.set_updated_at();
create trigger reviews_set_updated_at before update on public.reviews for each row execute function private.set_updated_at();
create trigger store_settings_set_updated_at before update on public.store_settings for each row execute function private.set_updated_at();

alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.phone_models enable row level security;
alter table public.product_phone_models enable row level security;
alter table public.customers enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.customizations enable row level security;
alter table public.coupons enable row level security;
alter table public.reviews enable row level security;
alter table public.store_settings enable row level security;

revoke all on public.products, public.product_images, public.phone_models, public.product_phone_models,
  public.customers, public.addresses, public.orders, public.order_items, public.customizations,
  public.coupons, public.reviews, public.store_settings from anon, authenticated;
grant select on public.products, public.product_images, public.phone_models, public.product_phone_models, public.reviews, public.store_settings to anon, authenticated;
grant select, insert, update on public.customers to authenticated;
grant select, insert, update, delete on public.addresses to authenticated;
grant select on public.orders, public.order_items, public.customizations to authenticated;
grant insert on public.reviews to authenticated;

create policy products_public_read on public.products for select to anon, authenticated using (status = 'active');
create policy product_images_public_read on public.product_images for select to anon, authenticated
using (exists (select 1 from public.products p where p.id = product_id and p.status = 'active'));
create policy phone_models_public_read on public.phone_models for select to anon, authenticated using (status = 'active');
create policy product_phone_models_public_read on public.product_phone_models for select to anon, authenticated
using (available and exists (select 1 from public.products p where p.id = product_id and p.status = 'active') and exists (select 1 from public.phone_models m where m.id = phone_model_id and m.status = 'active'));

create policy customers_read_own on public.customers for select to authenticated using ((select auth.uid()) = id);
create policy customers_insert_own on public.customers for insert to authenticated with check ((select auth.uid()) = id);
create policy customers_update_own on public.customers for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy addresses_read_own on public.addresses for select to authenticated using ((select auth.uid()) = customer_id);
create policy addresses_insert_own on public.addresses for insert to authenticated with check ((select auth.uid()) = customer_id);
create policy addresses_update_own on public.addresses for update to authenticated using ((select auth.uid()) = customer_id) with check ((select auth.uid()) = customer_id);
create policy addresses_delete_own on public.addresses for delete to authenticated using ((select auth.uid()) = customer_id);

create policy orders_read_own on public.orders for select to authenticated using ((select auth.uid()) = customer_id);
create policy order_items_read_own on public.order_items for select to authenticated
using (exists (select 1 from public.orders o where o.id = order_id and o.customer_id = (select auth.uid())));
create policy customizations_read_own on public.customizations for select to authenticated using ((select auth.uid()) = customer_id);

create policy reviews_public_read on public.reviews for select to anon, authenticated using (status = 'approved');
create policy reviews_insert_own on public.reviews for insert to authenticated
with check ((select auth.uid()) = customer_id and status = 'pending' and verified_purchase = false);
create policy store_settings_public_read on public.store_settings for select to anon, authenticated using (is_public);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('product-images', 'product-images', true, 10485760, array['image/jpeg','image/png','image/webp','image/avif']),
  ('phone-mockups', 'phone-mockups', true, 20971520, array['image/jpeg','image/png','image/webp','image/avif']),
  ('customer-uploads', 'customer-uploads', false, 52428800, array['image/jpeg','image/png','image/webp','image/heic','image/heif']),
  ('custom-previews', 'custom-previews', false, 20971520, array['image/jpeg','image/png','image/webp']),
  ('print-ready', 'print-ready', false, 104857600, array['image/png','image/jpeg','application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy customer_uploads_read_own on storage.objects for select to authenticated
using (bucket_id = 'customer-uploads' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy customer_uploads_insert_own on storage.objects for insert to authenticated
with check (bucket_id = 'customer-uploads' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy customer_uploads_update_own on storage.objects for update to authenticated
using (bucket_id = 'customer-uploads' and owner_id = (select auth.uid())::text)
with check (bucket_id = 'customer-uploads' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy customer_uploads_delete_own on storage.objects for delete to authenticated
using (bucket_id = 'customer-uploads' and owner_id = (select auth.uid())::text);

create policy custom_previews_read_own on storage.objects for select to authenticated
using (bucket_id = 'custom-previews' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy custom_previews_insert_own on storage.objects for insert to authenticated
with check (bucket_id = 'custom-previews' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy custom_previews_update_own on storage.objects for update to authenticated
using (bucket_id = 'custom-previews' and owner_id = (select auth.uid())::text)
with check (bucket_id = 'custom-previews' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy custom_previews_delete_own on storage.objects for delete to authenticated
using (bucket_id = 'custom-previews' and owner_id = (select auth.uid())::text);

-- No client write policies exist for public catalog assets or print-ready files.
-- Those operations intentionally require the server-only secret-key client.
