import {createSupabaseBrowserClient} from './client';
import type {BagItem,Order} from '@/components/StoreProvider';
import type {CustomerProfile,PaymentMethod,ShippingAddress} from '@/lib/commerce';

export async function updateRemoteProfile(userId:string,profile:CustomerProfile){const supabase=createSupabaseBrowserClient();const{error}=await supabase.from('customers').update({full_name:profile.name,email:profile.email,phone:profile.phone}).eq('id',userId);if(error)throw error}

export async function saveRemoteAddress(userId:string,address:ShippingAddress&{id?:string;label?:string;isDefault?:boolean},customer:CustomerProfile){const supabase=createSupabaseBrowserClient();if(address.isDefault)await supabase.from('addresses').update({is_default:false}).eq('customer_id',userId);const row={customer_id:userId,label:address.label||'Home',recipient_name:customer.name,phone:customer.phone,line1:address.line1,line2:address.line2||null,landmark:address.landmark||null,city:address.city,state:address.state,postal_code:address.pin,country_code:'IN',is_default:!!address.isDefault};const query=address.id?supabase.from('addresses').update(row).eq('id',address.id):supabase.from('addresses').insert(row);const{error}=await query;if(error)throw error}
export async function deleteRemoteAddress(id:string){const{error}=await createSupabaseBrowserClient().from('addresses').delete().eq('id',id);if(error)throw error}
export async function setRemoteDefaultAddress(userId:string,id:string){const supabase=createSupabaseBrowserClient();const reset=await supabase.from('addresses').update({is_default:false}).eq('customer_id',userId);if(reset.error)throw reset.error;const{error}=await supabase.from('addresses').update({is_default:true}).eq('id',id);if(error)throw error}

export async function placeRemoteOrder(input:{customer:CustomerProfile;shippingAddress:ShippingAddress;paymentMethod:PaymentMethod;items:BagItem[]}){const supabase=createSupabaseBrowserClient();const payload={customer:{full_name:input.customer.name,email:input.customer.email,phone:input.customer.phone},shipping_address:{recipient_name:input.customer.name,phone:input.customer.phone,line1:input.shippingAddress.line1,line2:input.shippingAddress.line2,landmark:input.shippingAddress.landmark,city:input.shippingAddress.city,state:input.shippingAddress.state,postal_code:input.shippingAddress.pin,country_code:'IN'},payment_method:input.paymentMethod,items:input.items.map(item=>({product_slug:item.productId,phone_model_slug:item.device,quantity:item.quantity,item_type:item.type||'ready-design',fixed_design_id:item.fixedDesignId||null,design_state:item.design?.customization||null,preview:item.design?.preview||null}))};const{data,error}=await supabase.rpc('place_order',{payload});if(error)throw error;return data}

export async function loadRemoteAccount(userId:string){const supabase=createSupabaseBrowserClient();const[customerResult,addressResult,orderResult,productResult,modelResult]=await Promise.all([supabase.from('customers').select('id,email,phone,full_name').eq('id',userId).single(),supabase.from('addresses').select('*').eq('customer_id',userId).order('created_at'),supabase.from('orders').select('*').eq('customer_id',userId).order('created_at',{ascending:false}),supabase.from('products').select('id,slug,name'),supabase.from('phone_models').select('id,slug')]);if(customerResult.error)throw customerResult.error;if(addressResult.error)throw addressResult.error;if(orderResult.error)throw orderResult.error;const orderIds=orderResult.data.map(order=>order.id),itemsResult=orderIds.length?await supabase.from('order_items').select('*').in('order_id',orderIds):{data:[],error:null};if(itemsResult.error)throw itemsResult.error;const customer:CustomerProfile={name:customerResult.data.full_name||'',email:customerResult.data.email||'',phone:customerResult.data.phone||'',address:''};const productMap=new Map((productResult.data||[]).map(product=>[product.id,product])),modelMap=new Map((modelResult.data||[]).map(model=>[model.id,model.slug]));const addresses=addressResult.data.map(row=>({id:row.id,label:row.label||'Home',line1:row.line1,line2:row.line2||'',landmark:row.landmark||'',city:row.city,state:row.state,pin:row.postal_code,isDefault:row.is_default}));const orders:Order[]=orderResult.data.map(row=>{const shipping=(row.shipping_address||{}) as Record<string,string>;return{id:`CC-${String(row.order_number).padStart(8,'0')}`,date:row.created_at,items:(itemsResult.data||[]).filter(item=>item.order_id===row.id).map(item=>{const product=productMap.get(item.product_id||'');return{key:item.id,productId:product?.slug||item.product_id||'',productName:item.product_name,device:modelMap.get(item.phone_model_id||'')||'',color:'Clear',quantity:item.quantity,type:item.item_type,unitPrice:item.unit_price,fixedDesignId:item.fixed_design_id||undefined}}),subtotal:row.subtotal,shipping:row.shipping_amount,discount:row.discount_amount,codFee:row.cod_fee,total:row.total,clans:[],customer,shippingAddress:{line1:shipping.line1||'',line2:shipping.line2||'',landmark:shipping.landmark||'',city:shipping.city||'',state:shipping.state||'',pin:shipping.postal_code||''},paymentMethod:(row.payment_method||'Online Payment') as PaymentMethod,paymentStatus:row.payment_status==='paid'?'Paid':'Not processed',status:row.status==='new'?'New':row.status,trackingId:row.tracking_id||undefined,courier:row.courier||undefined,adminNote:row.admin_note||undefined} as Order});return{customer,addresses,orders}}
